name: CI

on:
  push:
    paths-ignore:
      - '.vscode'
      - 'README.md'
  pull_request:
    branches: ["*"]
    paths-ignore:
      - '.vscode'
      - 'README.md'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: "Build with devkitARM"
    outputs:
      commit_tag: ${{ steps.build.outputs.commit_tag }}
      commit_message: ${{ steps.build.outputs.commit_message }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Build
        run: make
      - name: "Upload dist artefact"
        uses: actions/upload-artifact@v2
        with:
          name: "dist"
          path: dist/*
      - name: "Upload build artefact"
        uses: actions/upload-artifact@v2
        with:
          name: "build"
          path: build/*