name: CI

on:
  push:
    paths-ignore:
      - '.vscode'
      - 'README.md'
      - 'TODO.md'
  pull_request:
    branches: ["*"]
    paths-ignore:
      - '.vscode'
      - 'README.md'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: "Build with devkitARM"
    outputs:
      commit_tag: ${{ steps.build.outputs.commit_tag }}
      commit_message: ${{ steps.build.outputs.commit_message }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Build
        run: make

      - name: "Upload build artefact"
        uses: actions/upload-artifact@v2
        with:
          name: "build"
          path: build/*

      - name: "Upload base artefact"
        uses: actions/upload-artifact@v2
        with:
          name: "base"
          path: dist/turnip-project.nds

      - name: "Upload r4 artefact"
        uses: actions/upload-artifact@v2
        with:
          name: "r4"
          path: dist/patch/turnip-project-r4.nds
      
      - name: "Upload mpcf artefact"
        uses: actions/upload-artifact@v2
        with:
          name: "mpcf"
          path: dist/patch/turnip-project-mpcf.nds
      
      - name: "Upload fat image"
        uses: actions/upload-artifact@v2
        with:
          name: "fat"
          path: dist/fat/drastic_dldi.img