name: CI

on:
  push:
    branches: ["master"]
    paths-ignore:
      - '.vscode'
      - 'README.md'
      - 'TODO.md'
  pull_request:
    branches: ["*"]
    paths-ignore:
      - '.vscode'
      - 'README.md'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: "Build with devkitARM"
    outputs:
      commit_tag: ${{ steps.build.outputs.commit_tag }}
      commit_message: ${{ steps.build.outputs.commit_message }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Clean
        run: make clean
        
      - name: Build
        run: make